"""create pesanan table and update to_dict

Revision ID: 53be8d54e916
Revises: 310ed53680a8
Create Date: 2025-05-24 23:30:15.387602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53be8d54e916'
down_revision = '310ed53680a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesanan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_pelanggan', sa.String(length=255), nullable=False),
    sa.Column('nomor_hp', sa.String(length=20), nullable=True),
    sa.Column('jenis_layanan', sa.Enum('cuci_setrika', 'cuci_saja', 'setrika_saja', name='jenis_layanan_enum'), nullable=False),
    sa.Column('kategori_layanan', sa.Enum('kiloan', 'satuan', name='kategori_layanan_enum'), nullable=False),
    sa.Column('jumlah', sa.Float(), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('dilaundry', 'siap_diambil', 'selesai', name='status_pesanan_enum'), nullable=False),
    sa.Column('tanggal_masuk', sa.DateTime(), nullable=False),
    sa.Column('tanggal_keluar', sa.DateTime(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pesanan'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pesanan')
    # ### end Alembic commands ###
